apiVersion: v1
kind: ServiceAccount
metadata:
  name: main-mape-service-account
  namespace: development
---
apiVersion: v1
kind: Service
metadata:
  name: main-mape-service
  namespace: development
spec:
  selector:
    app: main-mape
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
