apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: development
spec:
  replicas: 0
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
